const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const path = require('path');

const app = express();
const PORT = 3000;

app.use(cors());
app.use(bodyParser.json());
app.use(express.static(path.join(__dirname, '../public')));

app.post('/api/generate', (req, res) => {
    try {
        const { 
            title, axisX, axisY, type, 
            style, color, data,
            grid, thickness, legendPos, legendLabel
        } = req.body;

        const rawColor = color || '#0000ff';
        const cleanHex = rawColor.replace('#', '').toUpperCase();

        let pgf = `% Generated by PGF GenService\n`;
        pgf += `\\definecolor{myGraphColor}{HTML}{${cleanHex}}\n`;
        
        pgf += `\\begin{tikzpicture}\n`;
        pgf += `    \\begin{axis}[\n`;
        pgf += `        title={${title || 'Графік'}},\n`;
        pgf += `        xlabel={${axisX || 'X'}},\n`;
        pgf += `        ylabel={${axisY || 'Y'}},\n`;
        
        if (grid && grid !== 'none') pgf += `        grid=${grid},\n`;
        if (legendLabel && legendPos) pgf += `        legend pos=${legendPos},\n`;

        if (type === 'bar') {
            pgf += `        ybar,\n`;
            pgf += `        bar width=15pt,\n`;
        }
        
        pgf += `        width=12cm,\n`;
        pgf += `    ]\n`;

        let plotOptions = `color=myGraphColor`;
        
        if (type === 'bar') {
            plotOptions += `, fill=myGraphColor!50`;
        }
        
        if (thickness && thickness !== 'normal') plotOptions += `, ${thickness}`;

        if (type === 'scatter') {
            plotOptions += `, mark=*, only marks`;
        } else if (type === 'line') {
            if (style === 'dashed') plotOptions += `, dashed`;
            if (style === 'dotted') plotOptions += `, dotted`;
            plotOptions += `, mark=*`; 
        } else if (type === 'bar') {
            plotOptions += `, no markers`; 
        }

        pgf += `    \\addplot[${plotOptions}] coordinates {\n`;

        if (Array.isArray(data)) {
            data.forEach(p => {
                pgf += `        (${p.x},${p.y})\n`;
            });
        }

        pgf += `    };\n`;

        if (legendLabel) pgf += `    \\addlegendentry{${legendLabel}}\n`;

        pgf += `    \\end{axis}\n`;
        pgf += `\\end{tikzpicture}`;

        res.json({ success: true, pgf: pgf });

    } catch (error) {
        console.error(error);
        res.status(500).json({ success: false, error: 'Помилка генерації' });
    }
});

app.listen(PORT, () => {
    console.log(`Сервер запущено: http://localhost:${PORT}`);
});